variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: cimverter-dev
  DOCKER_TAG_OMC: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_OMC: omc-dev-rse

stages:
  - prepare
  - test
  - checkmodel

# build the docker img in which we want to test. normally we want a dockerfile with all dependencies which we just include
docker-cimverter:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} -f ./Docker/Dockerfile.cimverter .
    - docker images
  only: 
    - rse
    - release
    - master
    - powerfactory
    - cgmes
  tags:
    - shell

docker-omc:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_OMC}:${DOCKER_TAG_OMC} -f ./Docker/Dockerfile.omc .
    - docker images
  tags:
    - shell
  only:
    - rse 
    - release
    - master
    - powerfactory
    - cgmes
# clone libcimpp in our projekt. compile and run the tests.

# Template
.test: &test
  stage: test
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker

  before_script:
    - apt-get update -qq && apt-get install -y -qq git 
    - git --version
    - rm -rf libcimpp/
    - git clone --recursive https://${GITLAB_USERLIBCIMPP}:${GITLAB_TOKENLIBCIMPP}@git.rwth-aachen.de/acs/public/cim/cimpp/libcimpp.git/ libcimpp/   
    - cd libcimpp
    - git rev-parse HEAD
    - cd ..
    - mkdir -p build && cd build
    - cmake .. -DUSE_CIM_VERSION:STRING=${CIM_VERSION}
    - make -j8
  script:
    - cd ../test/
    - ./testFiles.py ${CIM_VERSION}
    - ls -l
  artifacts:
    paths:
      - test/outputs/${CIM_VERSION}
  only:
    - master 
    - release
    - rse
    - powerfactory
    - cgmes


test-CGMES:
  <<: *test
  variables:
    CIM_VERSION: CGMES_2.4.15_27JAN2020

test-17v23:
  <<: *test
  variables:
    CIM_VERSION: IEC61970_17v23_IEC61968_13v11


.checkmodel: &checkmodel
  stage: checkmodel
  image: ${DOCKER_IMAGE_OMC}:${DOCKER_TAG_OMC}
  dependencies:
    - test-17v23
    - test-CGMES
  script:
    - pwd
    - cp test/outputs/${CIM_VERSION}/*.mo .
    - ls -l
    - git clone --recursive https://${GITLAB_USERMODPOWERSYSTEMS}:${GITLAB_TOKENMODPOWERSYSTEMS}@git.rwth-aachen.de/acs/core/simulation/modpowersystems
    - omc test/scripts/test_cigre.mos
    - omc test/scripts/test_slack.mos
  tags:
    - docker
  only:
    - rse
    - master
    - release
    - powerfactory
    - cgmes

checkmodel-CGMES:
  <<: *checkmodel
  variables:
    CIM_VERSION: CGMES_2.4.15_27JAN2020    

checkmodel-17v23:
  <<: *checkmodel
  variables:
    CIM_VERSION: IEC61970_17v23_IEC61968_13v11
